db:
  image: mysql
  container_name: lumen_avatar_mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
cache:
  image: memcached
  container_name: lumen_avatar_cache
php:
  image: msimone/lumen-avatar-php:latest
  volumes:
    - ./src:/app
  working_dir: /app
  command: php-fpm
  container_name: lumen_avatar_php
  links:
    - db
    - cache
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: SomeRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: secret
    MEMCACHED_HOST: cache
    CACHE_DRIVER: file
    IMG_DIR_AVATAR: "/app/public/avatar"
    IMG_DIR_AVATAR_IMG: "/app/public/avatar/images"
    MOCK_DIR_IMG: "/app/tests/images"
    MAIL_DRIVER: smtp
    MAIL_HOST: smtp.gmail.com
    MAIL_PORT: 587
    MAIL_FROM_NAME: "Avatar Team"
    MAIL_USERNAME: unemail@gmail.com
    MAIL_PASSWORD: 
    MAIL_ENCRYPTION: tls
nginx:
  image: msimone/lumen-avatar-nginx:latest
  command: nginx -g "daemon off;"
  container_name: lumen_avatar_nginx
  volumes:
    - ./src/:/app
  links:
    - php
  ports:
    - "80:80"
